import type { FlowerCard as FlowerCardType } from "../types/FlowerCard";

export const demoCards: FlowerCardType[] = [
    {
        cardId: 1,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower1.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#F4B086", "#FBD3B1", "#F0816F", "#F0816F"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower1.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower2.png",
        },
        message: "Congratulations!",
        sender: "Ran",
        receiver: "Won",

    },
    {
        cardId: 2,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower2.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFF3FF", "#FFB5B1", "#FDCE85", "#FFF3FF"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower2.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower2.png",
        },
        message: "With Love",
        sender: "Hwi",
        receiver: "Hye",
    },
    {
        cardId: 3,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower3.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFF3FF", "#FFD2DA", "#EDEFD0", "#E4E1F3"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower3.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower3.png",
        },
        message: "Happy Birthday!",
        sender: "Jeong",
        receiver: "Hoon",
    },
    {
        cardId: 4,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower4.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFBA69", "#FFF096", "#FFFCCB", "#FFB8A1"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower4.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower4.png",
        },
        message: "Thank You!",
        sender: "Jay",
        receiver: "Min",
    },
    {
        cardId: 5,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower5.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#D6E8F9", "#FCFFFD", "#FEE5D6", "#D6E9F6"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower5.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower5.png",
        },
        message: "Good Luck!",
        sender: "Seol",
        receiver: "Jong",
    },
    {
        cardId: 6,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower6.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#C5CBD8", "#C2F6F6", "#83A9E9", "#D6E5F1"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower6.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower6.png",
        },
    },
    {
        cardId: 7,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower7.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFF7DF", "#FCBE00", "#FFE85A", "#FFD2BC"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower7.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower7.png",
        },
    },
    {
        cardId: 8,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower7.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFF3FF", "#FFA9B7", "#FFB5B1", "#FFB5B1"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower8.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower8.png",
        },
    },
    {
        cardId: 9,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower9.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#E5F0ED", "#EFD8FF", "#9EC1F0", "#FFFEF0"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower9.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower9.png",
        },
    },
    {
        cardId: 10,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower10.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFF06B", "#FFF76D", "#FBEFCD", "#FFB52F"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower10.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower10.png",
        },
    },
    {
        cardId: 11,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower11.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FDF8EA", "#F6FF9C", "#E3DAFF", "#FFE198"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower11.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower11.png",
        },
    },
    {
        cardId: 12,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower12.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFDD9A", "#FFDFD4", "#FFA881", "#CFC02D"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower12.png",
        },
        subFlower: {
            flowerId: 2,
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower12.png",
        },
    },
    {
        cardId: 13,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower13.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#FFF3FF", "#FFA9B7", "#C5DCFF", "#8BAEFF"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower13.png",
        },
        subFlower: {
            flowerId: 2, 
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower13.png",
        },
    },
    {
        cardId: 14,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower14.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#E8D2FF", "#FCEBB1", "#FFC4FF", "#FFB5B1"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower14.png",
        },
        subFlower: {
            flowerId: 2, 
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower14.png",
        },
    },
    {
        cardId: 15,
        title: "축하의 마음을 전해요",
        imageUrl: "/assets/demo/flowers/flower15.png",
        imageSource: "custom",
        floriography: "사랑과 감사의 마음을 담아",
        whoType: "myself",
        whoLabel: "친구",
        whenType: "birthday",
        whenLabel: "생일",
        emotionTypes: ["joy", "love"],
        emotionLabels: ["기쁨", "사랑"],
        bouquetSize: "medium",
        bouquetLabel: "중간",
        wrappingType: "ribbon",
        wrappingLabel: "리본",
        price: 35000,
        designAssetId: 1,
        backgroundColors: ["#F0FDFD", "#8576FF", "#DBF2E9", "#9EC1F0"],
        mainFlower: {
            flowerId: 1,
            koreanName: "장미",
            englishName: "Rose",
            imageUrl: "/assets/demo/flowers/flower15.png",
        },
        subFlower: {
            flowerId: 2, 
            koreanName: "카네이션",
            englishName: "Carnation",
            imageUrl: "/assets/demo/flowers/flower15.png",
        },
    },
];